language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install codecov
install:
  - pip install -r requirements.txt  
script: python -m pytest # run tests